apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    move2kube.konveyor.io/service: redis
  name: redis
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: redis
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
          resources: {}
      restartPolicy: Always
      securityContext: {}
status: {}
