
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: api
    name: api
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - env:
                    - name: REDIS_URL
                      value: redis://redis:6379
                  image: quay.io/jefrankl/fibonacci-api:latest
                  imagePullPolicy: Always
                  name: api
                  ports:
                    - containerPort: 1234
                      protocol: TCP
                  resources: {}
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            securityContext: {}
status: {}

...
