
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: web
    name: web
spec:
    template:
        metadata:
            creationTimestamp: null
        spec:
            containers:
                - env:
                    - name: API_URL
                      value: http://api:1234/api
                  image: quay.io/jefrankl/fibonacci-web:latest
                  imagePullPolicy: Always
                  name: web
                  ports:
                    - containerPort: 80
                      protocol: TCP
                  resources: {}
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            securityContext: {}
status: {}

...
