
---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: redis
    name: redis
spec:
    internalTrafficPolicy: Cluster
    ports:
        - name: port-6379
          port: 6379
          protocol: TCP
          targetPort: 6379
    selector:
        move2kube.konveyor.io/service: redis
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}

...
