
---
apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: web
    name: web
spec:
    internalTrafficPolicy: Cluster
    ports:
        - name: port-8080
          port: 8080
          protocol: TCP
          targetPort: 80
    selector:
        move2kube.konveyor.io/service: web
    sessionAffinity: None
    type: ClusterIP
status:
    loadBalancer: {}

...
