apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: myproject-template
  generatename: ""
  namespace: ""
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels: {}
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
objects:
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: api
      name: api
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: REDIS_URL
                  value: redis://redis:6379
              image: quay.io/jefrankl/fibonacci-api:latest
              imagePullPolicy: Always
              name: api
              ports:
                - containerPort: 1234
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: redis
      name: redis
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - image: redis
              imagePullPolicy: Always
              name: redis
              ports:
                - containerPort: 6379
                  protocol: TCP
              resources: {}
          restartPolicy: Always
          securityContext: {}
    status: {}
  - apiVersion: serving.knative.dev/v1
    kind: Service
    metadata:
      creationTimestamp: null
      labels:
        move2kube.konveyor.io/service: web
      name: web
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - env:
                - name: API_URL
                  value: http://api:1234/api
              image: quay.io/jefrankl/fibonacci-web:latest
              imagePullPolicy: Always
              name: web
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
          imagePullSecrets:
            - name: quay-io-imagepullsecret
          restartPolicy: Always
          securityContext: {}
    status: {}
parameters: []
